## Arewa Data Science Academy
### Deep Learning Cohort 2.0

#### Name: Naziru Abdussalam Ibrahim
#### Email: naziruabdussalami@gmail.com
#### Title: Week 1 Solution

### Exercises Solution


2. Create a random tensor with shape (7, 7).


In [1]:
import torch
L = torch.rand(size=(7, 7))
print(L)
L.shape

tensor([[0.8794, 0.0290, 0.7533, 0.8945, 0.4890, 0.6924, 0.8406],
        [0.6552, 0.3526, 0.7270, 0.6223, 0.4067, 0.4127, 0.3124],
        [0.6847, 0.3701, 0.9259, 0.9908, 0.1293, 0.3896, 0.4739],
        [0.7271, 0.9887, 0.9504, 0.4204, 0.6451, 0.6529, 0.4234],
        [0.3813, 0.1637, 0.7610, 0.3058, 0.2411, 0.6241, 0.8597],
        [0.8825, 0.1943, 0.6267, 0.8234, 0.1545, 0.4783, 0.1161],
        [0.9525, 0.1890, 0.0397, 0.5915, 0.5225, 0.3796, 0.6267]])


torch.Size([7, 7])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [2]:

# another random tensor of (1, 7)
M = torch.rand(1, 7)

# matrix multiplication of N and M
N = torch.mm(L, M.T)
print(N)
N.shape

tensor([[2.9484],
        [2.3108],
        [2.7691],
        [2.9808],
        [2.0059],
        [2.4895],
        [2.0388]])


torch.Size([7, 1])

4. Set the random seed to 0 and do 2 & 3 over again.


In [3]:

# 0 random seed
torch.manual_seed(0)

O = torch.rand(size=(7, 7))
P = torch.rand(size=(1, 7))

# matrix multiplication
Q = torch.mm(O, P.T)
print(Q)
Q.shape

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


torch.Size([7, 1])

In [4]:
# 2 random seed
torch.manual_seed(2)

O = torch.rand(size=(7, 7))
P = torch.rand(size=(1, 7))

# matrix multiplication
Q = torch.mm(O, P.T)
print(Q)
Q.shape

tensor([[2.5722],
        [2.0592],
        [2.2192],
        [2.4909],
        [1.5547],
        [1.6152],
        [3.0816]])


torch.Size([7, 1])

In [5]:
# 3 random seed
torch.manual_seed(3)

O = torch.rand(size=(7, 7))
P = torch.rand(size=(1, 7))

# matrix multiplication
Q = torch.mm(O, P.T)
print(Q)
Q.shape

tensor([[1.1569],
        [2.7528],
        [2.7826],
        [1.8017],
        [0.8425],
        [1.8660],
        [1.6771]])


torch.Size([7, 1])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)


In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [4]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_P = torch.rand(size=(2,3)).to(device)
tensor_Q = torch.rand(size=(2,3)).to(device)
tensor_P, tensor_Q

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [6]:
# Perform matmul on tensor_P and tensor_Q
tensor_R = torch.mm(tensor_P, tensor_Q.T)
tensor_R, tensor_R.shape


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7.

In [7]:
# Using tensor methods for max and min
max_value = tensor_R.max()
min_value = tensor_R.min()
max_value, min_value


(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
arg_max = tensor_R.argmax()

# Find arg min
arg_min = tensor_R.argmin()
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [10]:
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_E = torch.flatten(tensor_D)

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
